[package]
authors = ["Alexander Korolev <kilork@yandex.ru>"]
build = "build.rs"
categories = ["network-programming",
              "asynchronous",
              "web-programming::http-server"]
description = """
actix-web static files as resources support.
"""
edition = "2018"
homepage = "https://github.com/kilork/actix-web-static-files"
keywords = ["actix", "http", "web", "static"]
license = "Unlicense OR MIT"
name = "actix-web-static-files"
readme = "README.md"
repository = "https://github.com/kilork/actix-web-static-files"
version = "0.2.1"

[dependencies]
actix-web = { version = "1.0", default-features = false }
actix-http = "0.2"
actix-service = "0.4.1"
bitflags = "1"
bytes = "0.4"
futures = "0.1"
derive_more = "0.15.0"
log = "0.4"
mime = "0.3"
mime_guess = "2.0"
percent-encoding = "2.1"
v_htmlescape = "0.4"
failure = "0.1"

[dev-dependencies]
actix-web = { version = "1.0", features=["rustls"] }

[build-dependencies]
actix-web = { version = "1.0", features=["rustls"] }
actix-http = "0.2"
actix-service = "0.4.1"
bitflags = "1"
bytes = "0.4"
futures = "0.1"
derive_more = "0.15.0"
log = "0.4"
mime = "0.3"
mime_guess = "2.0"
percent-encoding = "2.1"
v_htmlescape = "0.4"
failure = "0.1"
