[package]
authors = ["Alexander Korolev <kilork@yandex.ru>"]
build = "build.rs"
categories = ["network-programming",
              "asynchronous",
              "web-programming::http-server"]
description = """
actix-web static files as resources support.
"""
edition = "2018"
homepage = "https://github.com/kilork/actix-web-static-files"
keywords = ["actix", "http", "web", "static"]
license = "Unlicense OR MIT"
name = "actix-web-static-files"
readme = "README.md"
repository = "https://github.com/kilork/actix-web-static-files"
version = "0.3.0-alpha.3"

[dependencies]
actix-web = { version = "2.0.0-alpha.4", default-features = false }
actix-service = { version = "1.0.0-alpha.4", default-features = false }
futures = "0.3"
mime_guess = "2.0"
failure = "0.1"
path-slash = "0.1"

[build-dependencies]
actix-web = { version = "2.0.0-alpha.4", default-features = false }
actix-service = { version = "1.0.0-alpha.4", default-features = false }
futures = "0.3"
mime_guess = "2.0"
failure = "0.1"
path-slash = "0.1"
